add writing bundlewatch

diff --git a/.github/workflows/bundlewatch.yaml b/.github/workflows/bundlewatch.yaml
--- a/.github/workflows/bundlewatch.yaml
+++ b/.github/workflows/bundlewatch.yaml
@@ -20,41 +20,43 @@ jobs:
           node-version: 20
           cache: "npm"
 
-      # - name: Install dependencies
-      #   run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
-      # - name: Build
-      #   run: npm run build
+      - name: Build
+        run: npm run build
 
-      # - name: Run bundlewatch and capture output
-      #   id: bundlewatch
-      #   run: |
-      #     # Run bundlewatch and capture output, always return true to prevent workflow failure
-      #     OUTPUT=$(npm run bundlewatch || true)
+      - name: Run bundlewatch and capture output
+        id: bundlewatch
+        run: |
+          # Run bundlewatch and capture output, always return true to prevent workflow failure
+          OUTPUT=$(npm run bundlewatch || true)
 
-      #     # Escape newlines and special characters for GitHub Actions
-      #     OUTPUT="${OUTPUT//'%'/'%25'}"
-      #     OUTPUT="${OUTPUT//$'\n'/'%0A'}"
-      #     OUTPUT="${OUTPUT//$'\r'/'%0D'}"
+          # Escape newlines and special characters for GitHub Actions
+          OUTPUT="${OUTPUT//'%'/'%25'}"
+          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
+          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
 
-      #     # Set output variable
-      #     echo "result<<EOF" >> $GITHUB_OUTPUT
-      #     echo "$OUTPUT" >> $GITHUB_OUTPUT
-      #     echo "EOF" >> $GITHUB_OUTPUT
-      #   env:
-      #     BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
-      #     CI_REPO_OWNER: money-folder
-      #     CI_REPO_NAME: skarb-web
+          # Set output variable
+          echo "result<<EOF" >> $GITHUB_OUTPUT
+          echo "$OUTPUT" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+        env:
+          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
+          CI_REPO_OWNER: money-folder
+          CI_REPO_NAME: skarb-web
 
       - name: Comment PR
         uses: actions/github-script@v7
         with:
           script: |
+            const bundlewatchOutput = process.env.BUNDLEWATCH_OUTPUT;
+
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: '👋 Thanks for reporting!'
+             body: `### Bundlewatch Results\n\`\`\`\n${bundlewatchOutput}\n\`\`\``
             })
         env:
           BUNDLEWATCH_OUTPUT: ${{ steps.bundlewatch.outputs.result }}
